version: 0.2

env:
  variables:
    TF_IN_AUTOMATION: true
    TF_INPUT: 0
    AWS_REGION: eu-west-2
  parameter-store:
    ROLE_ARN: /codebuild/pttp-ci-infrastructure-core-pipeline/development/assume_role # tests hardcoded to only run in development

phases:
  install:
    commands:
      - wget -O terraform.zip https://releases.hashicorp.com/terraform/0.12.28/terraform_0.12.28_linux_amd64.zip
      - unzip terraform.zip
      - mv terraform /bin
      - wget -O gotestsum.tar.gz https://github.com/gotestyourself/gotestsum/releases/download/v0.5.1/gotestsum_0.5.1_linux_amd64.tar.gz
      - tar -xzvf gotestsum.tar.gz
      - mv gotestsum /bin

  build:
    commands:
      - ./scripts/aws-profile.sh "$ROLE_ARN" "test-session-$CODEBUILD_BUILD_NUMBER"
      - cd test && gotestsum --format testname --junitfile unit-tests.xml -- -timeout 30m

reports:
  terratestReports:
    files:
      - unit-tests.xml
    base-directory: test
