version: 0.2

env:
  variables:
    TF_IN_AUTOMATION: true
    TF_INPUT: 0
    TF_VAR_owner_email: pttp@justice.gov.uk
  parameter-store:
    TF_VAR_enable_peering:     "/codebuild/pttp-ci-infrastructure-core-pipeline/$ENV/enable_peering"
    TF_VAR_assume_role:        "/codebuild/pttp-ci-infrastructure-core-pipeline/$ENV/assume_role"
    TF_VAR_logging_cidr_block: "/codebuild/pttp-ci-infrastructure-core-pipeline/$ENV/logging_cidr_block"
    TF_VAR_ost_vpc_id:         "/codebuild/pttp-ci-infrastructure-core-pipeline/$ENV/ost_vpc_id"
    TF_VAR_ost_aws_account_id: "/codebuild/pttp-ci-infrastructure-core-pipeline/$ENV/ost_aws_account_id"
    TF_VAR_ost_vpc_cidr_block: "/codebuild/pttp-ci-infrastructure-core-pipeline/$ENV/ost_vpc_cidr_block"

phases:
  install:
    commands:
      - wget -O terraform.zip https://releases.hashicorp.com/terraform/0.12.27/terraform_0.12.27_linux_amd64.zip
      - unzip terraform.zip
      - mv terraform /bin

  build:
    commands:
      - terraform init -no-color --backend-config="key=terraform.$ENV.state"
      - terraform workspace new $ENV || true
      - terraform workspace select $ENV
      - terraform plan -no-color
      - terraform apply --auto-approve -no-color
