version: 0.2
phases:
  install:
    commands:
      - wget https://releases.hashicorp.com/terraform/0.12.24/terraform_0.12.24_linux_amd64.zip
      - unzip terraform_0.12.24_linux_amd64.zip
      - mv terraform /bin

      - echo "Prepare terraform file"
      - echo "terraform { " >> provider-output-backend.tf
      - echo "   backend \"s3\" { " >> provider-output-backend.tf
      - echo "   bucket = \"logging-codebuild-target-terraform-state\"" >> provider-output-backend.tf
      - echo "   key    = \"terraform.$ENV.tfstate\"" >> provider-output-backend.tf
      - echo "   region = \"eu-west-2\"" >> provider-output-backend.tf
      - echo "  }" >> provider-output-backend.tf
      - echo "}" >> provider-output-backend.tf

      - echo "provider \"aws\" {" >> provider-output-backend.tf
      - echo "  alias = \"env\"" >> provider-output-backend.tf
      - echo "  version = \"~> 2.52\"" >> provider-output-backend.tf
      - echo "  region  = \"eu-west-2\"" >> provider-output-backend.tf
      - echo "  assume_role {" >> provider-output-backend.tf
      - echo "    role_arn = \"$ASSUME_ROLE_ARN\"" >> provider-output-backend.tf
      - echo "  }" >> provider-output-backend.tf
      - echo "}" >> provider-output-backend.tf

      - cat provider-output-backend.tf

      - terraform init
  build:
    commands:
      - terraform init -no-color
      - terraform apply --auto-approve -no-color -input=false -var="environment=$ENV" -var="owner-email=pttp@justice.gov.uk" -var="shared_services_account_arn=$ASSUME_ROLE_ARN"